call mvn clean install -f ./dependencies/pom.xml
call mvn clean install -f ./exceptions/pom.xml
call mvn clean install -f ./security/pom.xml
call mvn clean install -f ./audit/pom.xml
call mvn clean install -f ./aws/pom.xml
call mvn clean install -f ./core/pom.xml
call mvn clean install -f ./database/pom.xml
call mvn clean install -f ./smartystreets/pom.xml
call mvn clean install -f ./parent/pom.xml
